### ISSUE TITLE
Initial review

### ISSUE THREAD

**Issue by tonygilkerson** [claygilk/k8s-bookshelf#1]
This issue is just a place to to park some review comments.

* Having the front-end, api and db in the same project is ok for learning but in a larger effort at work you would probably have a separate project for each, but I think you know that already...
* about the organization of the files in the k8s folder.  What you have if good, but often it is easier to have files organized by k8s resource types.  So for example you might have a `deployment.yaml` and a `services.yaml` file.  You can put several resources in a single file you just need to put `---` between each like:

```yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
```
* I would remove `creationTimestamp` and `status` from your manifests.  You will never set them.  They are set by the system at  deploy time but here they are just noise.
* I would also remove things that are empty `""` or `{}` such as `strategy: {}` and `resources: {}`  empty field are ignored by the system.  So after `kubectl apply` if you look you will not see `strategy` or `resources`.  Maybe you have them here to remind yourself you plan to add them at some point in the future... if so then ignore my comment but remember empty fields are ignored
*  I like how you got started with your deployment, using the `kubectl` command... what you have is a deployment that can start/run a container but you will need to expose its ports before you can create a working service.  Let's talk about your UI for example, but the same goes for your api and db.
* I see your UI is running a web-server and listening on port 8080 in the container.  Therefore, you need to expose that port on the deployment

```yaml
     ...
      containers:
        - name: vue-bookshelf-depo
          image: claygilk/vue-bookshelf
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
        ...
```

Notice that I gave the port a name `http`.  In your service I would expose the service on 80 and point it to your pod's `http` port.  By using the port name your service does not have to know if you chose 8080, 3000, 5000 or whatever to run your container it just needs to point at the `http` port.  Your service should look something like this:

```yaml
...
spec:
  ports:
  - name: http # This is just a name
    port: 80 # service exposed on 80
    protocol: TCP
    targetPort: http # targets your pod on whatever it names as its http port
...
```

* My last comment is the number one thing developers do to show they don't understand networking :-)  Learn this and you will be ahead of the other devs with 10yrs javascript experience!  All network traffic occurs on an address and port things like 192.168.0.100:80 i.e. IP:Port.   All IP addresses are bound to a device like a network card that connects you to the world.   However `localhost` is just an alias for `127.0.0.1` and that is a special address.  It is not connected to a network card, it is bound to as special loopback interface.... bottom line, when you see localhost think to yourself, all this traffic is **LOCAL**.  With that in mind, In your UI container I see this:

```text
App running at:
 - Local:   http://localhost:8080/
```

That means your web server is only listening for local traffic.  You will not be able to reach that web server from your browser because that is not local traffic.  You will need to change your app to listen on `0.0.0.0:8080`, then rebuild and push a new image.  

Very good, talk to you later
