### ISSUE TITLE
Add ingress controller

### ISSUE THREAD

**Issue by tonygilkerson** [claygilk/k8s-bookshelf#2]
This issue is to describe how to expose an api behind your web server

## Install ingress controller

First install an ingress controller.  An ingress controller will allow you to create routing rules for ingress network traffic

```sh
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.2/deploy/static/provider/cloud/deploy.yaml
```

Give it a few minutes to download and install the nginx container then run the following to verify.  Notice the "EXTERNAL-IP" is 'localhost'.  When you run in the cloud this would be your domain name like foo.com.  Any request to local host ports 80 and 443 will be handled by this ingress controller.

```sh
kubectl -n ingress-nginx get svc ingress-nginx-controller
```

## Create Ingress Resource

Create a file in your `k8s` folder called `ingress.yaml` and past in the following content.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookshelf
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: vue-bookshelf-svc
            port:
              number: 8080
      - path: /api/(.*)
        pathType: Prefix
        backend:
          service:
            name: node-api-svc
            port:
              number: 80
 ```
 
Then deploy it into the cluster:

```
kubectl apply -f k8s/ingress/yaml
```

You can verify by running:

```sh
kubectl get ing
```

## Accessing your app

Now when you point your browser at the following you should see your bookshelf UI

http://localhost

> Note: you can now remove the node port from `vue-bookshelf-svc`

Use the following to access your API

http://localhost/api/

I don't know what endpoints your API exposes but if for example your api exposes a `books` endpoint then you would use the following URL

http://localhost/api/books

The `api` is removed and your api receives a request for `/books`

## Accessing the API from your web app

Notice the web app and the api are under the same domain, the web app can reach the api by doing something like the following:

```javascript

var apiURL = window.location.origin + /api

// get mybook
const response = await fetch(apiURL  + "/books/mybook");

```
